dist: releases
release:
  github:
    owner: ekristen
    name: satokens
  prerelease: auto
before:
  hooks:
    - go mod tidy
builds:
  - id: satokens
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w
      - -s
      - -X '{{ .ModulePath }}/pkg/common.SUMMARY={{ .Version }}'
      - -X '{{ .ModulePath }}/pkg/common.BRANCH={{ .Branch }}'
      - -X '{{ .ModulePath }}/pkg/common.VERSION={{ .Tag }}'
      - -X '{{ .ModulePath }}/pkg/common.COMMIT={{ .Commit }}'
archives:
  - id: satokens
    builds:
      - satokens
    name_template: "{{ .ProjectName }}-utils-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}"
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - id: satokens
    ids:
      - satokens
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/ekristen/satokens:{{ .Version }}
      - ghcr.io/ekristen/satokens:{{ replace .Branch "/" "-" }}-{{ .ShortCommit }}-{{ .Timestamp }}
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/ekristen/satokens"
      - "--platform=linux/amd64"
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    args:
      ["sign-blob", "--tlog-upload=false", "--key=cosign.key", "--output-signature=${signature}", "${artifact}"]
    artifacts: all
docker_signs:
  - artifacts: all
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: '{{ trimprefix .Summary "v" }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
